#!/usr/bin/env python3
"""Regenerate or verify MAKO Renderer's embedded spatial-scaling SPIR-V."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import struct
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parent.parent
SHADER = ROOT / "mako-render/src/shaders/spatial_scaling.comp"
OUTPUT = ROOT / "mako-render/src/shaders/spatial_scaling_spirv.hpp"
HASH_MANIFEST = ROOT / "mako-render/src/shaders/spatial_scaling_spirv.hashes"
VARIANTS = (
    ("spatialScalingRgba8Spirv", ()),
    ("spatialScalingRgba16fSpirv", ("-DMAKO_SCALING_RGBA16F=1",)),
)


def format_words(data: bytes) -> str:
    if len(data) % 4 != 0:
        raise SystemExit("Generated SPIR-V length is not word-aligned")
    words = struct.unpack(f"<{len(data) // 4}I", data)
    rows = []
    for offset in range(0, len(words), 6):
        values = ", ".join(
            f"0x{value:08x}" for value in words[offset:offset + 6]
        )
        rows.append(f"      {values},")
    return "\n".join(rows)


def source_digest() -> str:
    return hashlib.sha256(SHADER.read_bytes()).hexdigest()


def embedded_payload(header: str, symbol: str) -> bytes:
    match = re.search(
        rf"\b{re.escape(symbol)}\s*=\s*\{{(.*?)\n\s*\}};",
        header,
        flags=re.DOTALL,
    )
    if match is None:
        raise SystemExit(f"Embedded SPIR-V array is missing: {symbol}")
    values = re.findall(r"0x([0-9a-fA-F]{8})", match.group(1))
    if not values:
        raise SystemExit(f"Embedded SPIR-V array is empty: {symbol}")
    return b"".join(
        int(value, 16).to_bytes(4, byteorder="little") for value in values
    )


def check() -> None:
    header = OUTPUT.read_text(encoding="utf-8")
    source = source_digest()
    payloads = {
        symbol: embedded_payload(header, symbol)
        for symbol, _arguments in VARIANTS
    }
    recorded_source = re.search(
        r"^// spatial_scaling\.comp sha256:\n// ([0-9a-f]{64})$",
        header,
        flags=re.MULTILINE,
    )
    expected_manifest = (
        "# Generated by generate-spatial-scaling-spirv.py; do not edit.\n"
        "# source symbol source-sha256 payload-sha256\n"
        + "".join(
            f"spatial_scaling.comp {symbol} {source} "
            f"{hashlib.sha256(payloads[symbol]).hexdigest()}\n"
            for symbol, _arguments in VARIANTS
        )
    )
    if (
        recorded_source is None
        or recorded_source.group(1) != source
        or HASH_MANIFEST.read_text(encoding="utf-8") != expected_manifest
    ):
        raise SystemExit(
            "Embedded spatial-scaling SPIR-V is stale. Run "
            "engine/scripts/generate-spatial-scaling-spirv.py with "
            "glslangValidator available."
        )
    for symbol, payload in payloads.items():
        if payload[:4] != b"\x03\x02\x23\x07":
            raise SystemExit(
                f"Embedded spatial-scaling payload is not SPIR-V: {symbol}"
            )
    print("Embedded spatial-scaling SPIR-V source and payload hashes are current.")


def generate() -> None:
    source = source_digest()
    payloads: list[tuple[str, bytes]] = []
    with tempfile.TemporaryDirectory(prefix="mako-scaling-spirv-") as temp_dir:
        for symbol, arguments in VARIANTS:
            binary = Path(temp_dir) / f"{symbol}.spv"
            subprocess.run(
                [
                    "glslangValidator", "-V", "-Os", "--quiet", *arguments,
                    "-o", str(binary), str(SHADER),
                ],
                check=True,
            )
            payloads.append((symbol, binary.read_bytes()))

    header_lines = [
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        "",
        "// Generated from spatial_scaling.comp with glslangValidator -V -Os.",
        "// spatial_scaling.comp sha256:",
        f"// {source}",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace mako::layer::embedded {",
    ]
    for symbol, payload in payloads:
        header_lines.extend((
            f"    inline constexpr std::array<uint32_t, {len(payload) // 4}> "
            f"{symbol} = {{",
            format_words(payload),
            "    };",
        ))
    header_lines.extend(("}", ""))
    OUTPUT.write_text("\n".join(header_lines), encoding="utf-8")
    HASH_MANIFEST.write_text(
        "# Generated by generate-spatial-scaling-spirv.py; do not edit.\n"
        "# source symbol source-sha256 payload-sha256\n"
        + "".join(
            f"spatial_scaling.comp {symbol} {source} "
            f"{hashlib.sha256(payload).hexdigest()}\n"
            for symbol, payload in payloads
        ),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    if arguments.check:
        check()
    else:
        generate()


if __name__ == "__main__":
    main()
