"""
Auto-generated configuration schema components from shared_config.py
DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on build
"""

from typing import TypedDict, Dict, Any, Union
from enum import Enum
import sys
from pathlib import Path

# Import shared configuration constants
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from shared_config import CONFIG_SCHEMA_DEF, ConfigFieldType

# Field name constants for type-safe access
DLL = "dll"
ALLOW_FP16 = "allow_fp16"
FRAME_GENERATION_ENABLED = "frame_generation_enabled"
BASE_FPS_CAP = "base_fps_cap"
MULTIPLIER = "multiplier"
ADAPTIVE = "adaptive"
ADAPTIVE_AUTO_BASE_FPS_CAP = "adaptive_auto_base_fps_cap"
TARGET_FPS = "target_fps"
ADAPTIVE_MAX_MULTIPLIER = "adaptive_max_multiplier"
ADAPTIVE_STABLE_CADENCE = "adaptive_stable_cadence"
FLOW_SCALE = "flow_scale"
PERFORMANCE_MODE = "performance_mode"
PACING = "pacing"
ACTIVE_IN = "active_in"
GPU = "gpu"
DISABLE_MAKO = "disable_mako"
DISABLE_HDR_EXPOSURE = "disable_hdr_exposure"
EXTERNAL_VULKAN_LAYER = "external_vulkan_layer"
DISABLE_STEAMDECK_MODE = "disable_steamdeck_mode"
ENABLE_ZINK = "enable_zink"
FORCE_ALSA_AUDIO = "force_alsa_audio"


class ConfigurationData(TypedDict):
    """Type-safe configuration data structure - AUTO-GENERATED"""
    dll: str
    allow_fp16: bool
    frame_generation_enabled: bool
    base_fps_cap: int
    multiplier: int
    adaptive: bool
    adaptive_auto_base_fps_cap: bool
    target_fps: int
    adaptive_max_multiplier: int
    adaptive_stable_cadence: bool
    flow_scale: float
    performance_mode: bool
    pacing: str
    active_in: str
    gpu: str
    disable_mako: bool
    disable_hdr_exposure: bool
    external_vulkan_layer: str
    disable_steamdeck_mode: bool
    enable_zink: bool
    force_alsa_audio: bool


def get_script_parsing_logic():
    """Return the script parsing logic as a callable"""
    def parse_script_values(lines):
        script_values = {}
        for line in lines:
            line = line.strip()
            if not line or line.startswith("#") or not line.startswith("export "):
                continue
            if "=" in line:
                export_line = line[len("export "):]
                key, value = export_line.split("=", 1)
                key = key.strip()
                value = value.strip()

                # Auto-generated parsing logic:
                if key == "DISABLE_MAKO":
                        script_values["disable_mako"] = value == "1"
                if key == "MAKO_DISABLE_HDR_EXPOSURE":
                        script_values["disable_hdr_exposure"] = value == "1"
                if key == "MAKO_EXTERNAL_VULKAN_LAYER":
                        script_values["external_vulkan_layer"] = value
                if key == "SteamDeck":
                        script_values["disable_steamdeck_mode"] = value == "0"
                if key == "__GLX_VENDOR_LIBRARY_NAME" and value == "mesa":
                        script_values["enable_zink"] = True
                if key == "MESA_LOADER_DRIVER_OVERRIDE" and value == "zink":
                        script_values["enable_zink"] = True
                if key == "GALLIUM_DRIVER" and value == "zink":
                        script_values["enable_zink"] = True
                if key == "SDL_AUDIODRIVER" and value == "alsa":
                        script_values["force_alsa_audio"] = True

        return script_values
    return parse_script_values


def get_script_generation_logic():
    """Return the script generation logic as a callable"""
    def generate_script_lines(config):
        lines = []
        if config.get("disable_mako", False):
            lines.append("export DISABLE_MAKO=1")
        if config.get("disable_hdr_exposure", False):
            lines.append("export MAKO_DISABLE_HDR_EXPOSURE=1")
        external_vulkan_layer = config.get("external_vulkan_layer", "")
        lines.append(f"export MAKO_EXTERNAL_VULKAN_LAYER={external_vulkan_layer}")
        if config.get("disable_steamdeck_mode", False):
            lines.append("export SteamDeck=0")
        if config.get("enable_zink", False):
            lines.append("export __GLX_VENDOR_LIBRARY_NAME=mesa")
            lines.append("export MESA_LOADER_DRIVER_OVERRIDE=zink")
            lines.append("export GALLIUM_DRIVER=zink")
        if config.get("force_alsa_audio", False):
            lines.extend([
                "export SDL_AUDIODRIVER=alsa",
                'case ";${WINEDLLOVERRIDES:-};" in',
                '    *";winepulse.drv=d;"*) ;;',
                '    *) export WINEDLLOVERRIDES="${WINEDLLOVERRIDES:+$WINEDLLOVERRIDES;}winepulse.drv=d" ;;',
                "esac",
                'case ";${WINEDLLOVERRIDES:-};" in',
                '    *";winealsa.drv=b;"*) ;;',
                '    *) export WINEDLLOVERRIDES="${WINEDLLOVERRIDES:+$WINEDLLOVERRIDES;}winealsa.drv=b" ;;',
                "esac",
            ])
        return lines
    return generate_script_lines


ALL_FIELDS = ['dll', 'allow_fp16', 'frame_generation_enabled', 'base_fps_cap', 'multiplier', 'adaptive', 'adaptive_auto_base_fps_cap', 'target_fps', 'adaptive_max_multiplier', 'adaptive_stable_cadence', 'flow_scale', 'performance_mode', 'pacing', 'active_in', 'gpu', 'disable_mako', 'disable_hdr_exposure', 'external_vulkan_layer', 'disable_steamdeck_mode', 'enable_zink', 'force_alsa_audio']
